<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SpotifyAPI.Web" Version="7.4.2" />
    <PackageReference Include="YoutubeExplode" Version="6.6.1" />
  </ItemGroup>

</Project>
