<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="log4net" Version="3.3.2" />
    <PackageReference Include="SpotifyAPI.Web" Version="7.4.2" />
    <PackageReference Include="System.Data.SQLite" Version="2.0.4" />
    <PackageReference Include="YoutubeExplode" Version="6.6.1" />
  </ItemGroup>
	<ItemGroup>
		<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
			<_Parameter1>BackendTests</_Parameter1>
		</AssemblyAttribute>
	</ItemGroup>
  <ItemGroup>
    <None Update="Music.db">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
